language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
matrix:
  allow_failures:
    - julia: nightly
addons:
    apt_packages:
        - gfortran
notifications:
  email: false
git:
  depth: 99999999
  
before_script:
  - julia -e 'using Pkg; Pkg.add(PackageSpec(name="Compose", rev="master"))'
  - julia -e 'using Pkg; Pkg.add(PackageSpec(name="Gadfly", rev="master"))'
after_success:
  - julia -e 'using Pkg, MendelPlots; cd(joinpath(dirname(pathof(MendelPlots)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'


jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: osx
      script:
        - julia -e 'using Pkg; Pkg.add("Documenter")'
        - julia -e 'using MendelPlots; include(joinpath(dirname(pathof(MendelPlots)), "..", "docs", "make.jl"))'
      after_script: skip