language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.5
  - nightly
addons:
    apt_packages:
        - gfortran
notifications:
  email: false
git:
  depth: 99999999

#before_script:
#  - julia -e 'using Pkg; Pkg.add(PackageSpec(name="Compose", rev="master"))'
#  - julia -e 'using Pkg; Pkg.add(PackageSpec(name="Gadfly", rev="master"))'
after_success:
  - julia -e 'using Pkg, MendelPlots; cd(joinpath(dirname(pathof(MendelPlots)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder()); Coveralls.submit(process_folder())'

jobs:
  allow_failures:
    - julia: nightly
